env:
  es6: true
  mocha: true

plugins:
  - mocha

extends:
  - airbnb-base
  - plugin:mocha/recommended

rules:
  import/no-extraneous-dependencies:
    - error
    - devDependencies: true

  no-restricted-syntax: 0

  no-bitwise: 0

  mocha/no-mocha-arrows: 0
